github.com:
    users:
        AdamWS17:
            oauth_token: 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
    git_protocol: ssh
    oauth_token: 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
    user: AdamWS17
